[auth]
	# This is for the links a the bottom of login/join auth pages.
	or = "sau"
	join_link = "Înregistrează-te!"
	login_link = "Autentifică-te!"
	forgot_link = "Ai uitat Numele de Utilizator sau Parola"

# /login
[auth.login]
	page_title = "Conectați-vă la Game Jolt"

	twitter_button = "Conectați-vă prin Twitter"
	facebook_button = "Conectați-vă prin Facebook"

	username_label = "Nume de Utilizator"
	password_label = "Parolă"
	submit_button = "Conectați-vă"

	# Shows up if you enter an invalid user/password combination.
	invalid_login_error_html = "Numele de utilizator sau parola incorectă."

	# Login takes a while, so we show this for the loading text.
	# Can be quirky and fun! =]
	loading_message_count = "4"
	loading_message_1 = "Conectare la calculatorul principal..."
	loading_message_2 = "Calcularea valorii exacte lui π..."
	loading_message_3 = "Lansăm modulele de amuzament..."
	loading_message_4 = "Proiectarea matricei hoopla..."

# /join
[auth.join]
	page_title = "Alătură-te în Game Jolt - Cea Mai Mare Colecție de Jocuri Indie Făcute de către Oameni"

	twitter_button = "Înregistrează-te prin Twitter"
	facebook_button = "Înregistrează-te prin Facebook"

	# The lead text of the page.
	# Quirky and fun as it's the text to get them excited about signing up.
	# Let's try to keep it at 3 lines or less on the page.
	join_message_html_count = "2"
	join_message_html_1 = "Alăturăte nouă. Mwuahaha.<br>Noi avem jocuri.<br><strong><em>Mwuahahaha!</em></strong>"
	join_message_html_2 = "Alătură-te nouă pentru o călatorie în inima unei supernove făcute din jocuri."

	email_label = "Adresa de E-Mail"
	username_label = "Nume de Utilizator"
	password_label = "Parolă"

	submit_button = "Înregistrează-te"

# /join/almost
# After a successful sign up they land here.
# They still have to authorize their account.
[auth.join.almost]
	page_title = "Aproape gata!"
	heading = "@:auth.join.almost.page_title"
	body_html = """
	<p>Înainte de a te conecta la Game Jolt, trebuie sa verifici adresa de e-mail a contului tău.</p>
	<p>Am trimis un E-mail cu instrucțiunile de activare ale contului tău.</p>
	"""
	spam = "Dacă nu vezi un E-Mail în zece minute, te rugăm să verifici fișierul pentru spam. Este posibil ca acesta sa fi ajuns acolo!"
	urgency = "Reține faptul că ai o săptămână la dispoziție să îți activezi contul. După aceea, el va fi șters și va trebui să te înregistrezi din nou."

# You need to actually sign up to get a valid URL for this page.
# We only show a Growl on successful authorization and funnel off to the main site.
[auth.authorize]
	success_growl_title = "Cont Autorizat"
	success_growl = "Acum te redirecționam catre bordul tău de pe Game Jolt."

# /authorize/169219/62b17036174c87ee503fe0ef2902c79d/2
# The page that shows when their authorization fails.
# They shouldn't get here unless they clicked the link again after authorizing. Or if they are trying to cheat something.
[auth.authorize.invalid]
	page_title = "Cod de Autorizare Invalid"
	heading = "Autorizație Invalidă"
	body_html = """
	<p>Codul tău de autorizare este invalid.</p>
	<p>Vă rog sa vă asigurați că ați copiat și lipit întregul URL pe care vi l-am trimis.</p>
	"""

# /forgot
[auth.forgot]
	page_title = "Recuperarea datelor de autentificare "
	heading = "@:auth.forgot.page_title"

	email_help = "Lipiți adresa de E-Mail de pe contul vostru și vă vom trimite datele de autentificare prin E-Mail."
	email_label = "Adresa de E-Mail"
	submit_button = "Recuperarea Datelor"

	# If the email address they enter isn't a registered user, this shows up as an error message.
	invalid_email_error_html = """
	<p>Hmm, acea adresă de e-mail nu este in sistemul nostru. Poate că nu <a href="/join">te-ai înregistrat încă?</a>?</p>
	"""

# /forgot/sent
# For after they fill out the "forgot" form.
[auth.forgot.sent]
	page_title = "Date Trimise"
	heading = "@:auth.forgot.sent.page_title"
	body_html = "<p>Am trimis datele de înregistrare prin adresa de e-mail înregistrată.</p>"
	spam = "Dacă nu primești un e-mail în zece minute, te rugăm să verifici fișierul pentru spam. Este posibil ca acesta să fi ajuns acolo!"

# The URL for this gets sent in an email when they fill out the forgot login credentials page.
[auth.reset_password]
	page_title = "Schimbă Parola"
	heading = "@:auth.reset_password.page_title"

	password_help = "Dacă dorești să îți resetezi parola, introdu una nouă dedesubt.If you'd like to reset your password, enter a new one below."
	password_label = "Parolă Nouă"
	submit_button = "Schimbă Parola"

	# For when they successfully reset.
	# Will send them back to the login page after showing this Growl.
	success_growl_title = "Parolă Schimbată"
	success_growl = "Parola ta a fost schimbata. Acum te poți conecta cu cea nouă."


#####################
# Linked Account Auth

[auth.linked_account]

	# When they get returned back to GJ from FB/Twitter, etc. we do some processing of the login/sign up.
	# This is a generic loading message while we're doing our work.
	loading_message = "În curs de procesare. Vă rugăm așteptați..."

[auth.linked_account.facebook]

	# Generic failed message.
	failed_growl = "Conectare incapabiă prin Facebook."
	failed_growl_title = "Conectare nereușită"

	# For the rare case when FB doesn't give us an email address. This would be very rare if it did ever happen.
	no_email_growl = "Contul tău de Facebook nu a returnat nici o adresă de e-mail. Asigurați-vă că ați verificat-o prin Facebook."
	no_email_growl_title = "O nu!"

	# When someone tries to sign up with an FB account with an email address that exists on an existing GJ account.
	# In most cases this will probably be an accident where they signed up in the past
	# and then try signing up again with FB later on, but their email address is
	# registered on their old account.
	duplicate_email_growl = "Adresa de e-mail de pe acest cont de Facebook este în folosința. Poate că deja ai un cont?"
	duplicate_email_growl_title = "O nu!"

	# After a successful FB sign up.
	created_growl = "Contul tău a fost creat. Navigare netedă de acum încolo!"
	created_growl_title = "Cont Creat"

[auth.linked_account.twitter]

	# Generic failed message.
	failed_growl = "Conectare incapabiă prin Twitter."
	failed_growl_title = "Conectare nereușită"

	# When they submit the form and their account is set up with Twitter.
	created_growl = "Contul tău a fost creat. De acum îl puteți folosi!"
	created_growl_title = "Cont Creat"

# /login/finalize-twitter
# They get directed here when they sign up with a new twitter account and we require their email address.
[auth.linked_account.twitter.finalize]
	page_title = "E-mail Necesar"
	heading = "@:auth.linked_account.twitter.finalize.page_title"

	email_help = "Pentru a finaliza conectarea prin Twitter, vă rugăm să introduceți o adresă de e-mail validă."
	email_label = "Adresă de E-Mail"
	submit_button = "Completează Înregistrarea"

	# If they entered an email address that exists on another account.
	# In most cases this will probably be an accident where they signed up in the past
	# and then try signing up again with twitter later on, but their email address is
	# registered on their old account.
	duplicate_email_error_html = """
	<p>Adresa de e-mail introdusă este deja în folosință.</p>
	<p>Dacă ai deja un cont pe Game Jolt poti să te <a href="/login">conectezi aici</a>.</p>
	<p>Dacă v-ați uitat datele de conectare, puteți să le <a href="/forgot">recuperați aici</a>.</p>
	"""
